/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package part1;

import part2.*;
import java.awt.Graphics;

/**
 *
 * @author seanzhang
 */
public class FractalsPanel extends javax.swing.JPanel {
    double sizeFactor=0.5;
    double angleFactor=90;
    int depth = 50;
    int length = 150;
    /**
     * Creates new form FractalsPanel
     */
    public FractalsPanel() {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        treeFractal(g,depth,this.getWidth()/2,this.getHeight(),length,Math.toRadians(angleFactor));
        
        
    }
    
    public void treeFractal(Graphics g, int depth, int x, int y, double length, double angle){
        //calculate the ending x,y coordinates for this line segment.
        //As we are moving up, we subtract from the current base coordinates 
        //The formula used to determine end points by definition of sin and cos
        int x1 = x - (int)(Math.cos(angle)*length);
        int y1 = y - (int)(Math.sin(angle)*length);
        //actually draw the line
        g.drawLine(x,y,x1,y1);
        //if we have more depth to go, recurse
        if (depth > 0){
            treeFractal(g,depth-1,x1,y1,length*sizeFactor,angle+angleFactor);
            treeFractal(g,depth-1,x1,y1,length*sizeFactor,angle-angleFactor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
